version: '3.8'

services:
  app:
    build: .
    ports:
      - "${SERVICE_PORT:-3000}:${SERVICE_PORT:-3000}"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/comment-service
      - NODE_ENV=production
      - SERVICE_PORT=${SERVICE_PORT:-3000}
    depends_on:
      - mongodb
    networks:
      - traefik-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - traefik-network

volumes:
  mongodb_data: 